version: "3.9"

services:
  algorithm_service:
    build: ./services/algorithm_service
    container_name: algorithm_service
    ports: ["8888:8000"]
    volumes:
      - ./data:/app/data
    restart: always