
services:
  app:
    image: huo-infer-v8:v4
    container_name: multi_payload_app
    working_dir: /workspace
    runtime: nvidia # GPU
    ports:
      - "9001:9000"  
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      OMP_NUM_THREADS: "8"
      PYTHONUNBUFFERED: "1"
      NVIDIA_VISIBLE_DEVICES: "all" # GPU
      NVIDIA_DRIVER_CAPABILITIES: "all" # GPU
      
      MYSQL_HOST: "172.17.0.1"
      MYSQL_PORT: "3306"
      MYSQL_USER: "air"
      MYSQL_PASSWORD: "123"
      MYSQL_DATABASE: "agent"
      
      # ========================
      # Ollama
      # ========================
      LLM_ENABLED: "true"
      OLLAMA_BASE_URL: "http://host.docker.internal:11434"
      OLLAMA_MODEL: "qwen3:14b"
      OLLAMA_TIMEOUT: "300"
    
    volumes:
      - .:/workspace                      # 映射根目录，调度器代码热更新
      - ./services/algorithm_service:/app # 映射算法目录，算法代码热更新
      - ./data:/app/data                  # 映射数据目录
      - "/home/air:/home/air"
    deploy:                             #  GPU 
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command:
      - /bin/sh
      - -c
      - |
        set -eu

        # 1. 环境变量与依赖配置
        export LD_LIBRARY_PATH="/mnt/ww/opencv460/lib64:/usr/local/lib:$${LD_LIBRARY_PATH:-}"
        export PYTHONPATH="/workspace:/app:$${PYTHONPATH:-}"

        # 2. 后台启动算法服务 (开启 --reload)
        cd /app
        chmod +x /app/myprogram || true
        python -m uvicorn app:app --host 0.0.0.0 --port 8888 --reload --reload-dir /app &
        api_pid=$$!
        trap 'kill "$$api_pid" 2>/dev/null || true' EXIT

        # # mock 
        # cd /workspace/services/mock_all_service
        # python -m uvicorn app:app --host 0.0.0.0 --port 8888 --reload --reload-dir /workspace/services/mock_all_service &
        # api_pid=$$!
        # trap 'kill "$$api_pid" 2>/dev/null || true' EXIT

        # 3. 等待算法服务就绪
        echo "Waiting for algorithm service to start..."
        retry_count=0
        until python -c "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8888/docs', timeout=2).close()" >/dev/null 2>&1; do
          retry_count=$$((retry_count + 1))
          if [ "$$retry_count" -ge 60 ]; then
            echo "algorithm service not ready" >&2
            exit 1
          fi
          sleep 1
        done
        echo "Algorithm service is ready!"

        # 4.  前台启动主调度器 API (开启 --reload)
        cd /workspace
        python -m uvicorn api_main:app --host 0.0.0.0 --port 9000 --reload --reload-dir /workspace

    restart: "no"